_target_: config.SentenceClassificationConfig
backbone_model: 'google-bert/bert-base-multilingual-cased'
embedding_dim: 768
output_dir: '${path:checkpoints/sentence-classification}'

learning_rate: 0.0001  # 1e-4
batch_size: 256
sentences_dataset: 'stanfordnlp/imdb'

config_to_train: 'pag-score' # 'baseline'
epochs: 200
lambda_pag: 2.0
lambda_ce: 0.5
