_target_: config.SentenceClassificationConfig
backbone_model: 'distilbert/distilbert-base-multilingual-cased'
embedding_dim: 768
output_features: 2
output_dir: '${path:checkpoints/sentence-classification}'

learning_rate: 0.0001
batch_size: 256
sentences_dataset: 'stanfordnlp/imdb'

resume_training: False

config_to_train: 'pag-score-similar-features'  # See all possible values in train.py
epochs: 100
lambda_pag: 2.5
lambda_ce: 0.5
pag_samples_per_class: 24
