_target_: config.SentenceClassificationConfig
backbone_model: 'google-bert/bert-base-multilingual-cased'
embedding_dim: 768
num_classes: 6
output_dir: '${path:checkpoints/sentence-classification}'

learning_rate: 0.0001
batch_size: 256
sentences_dataset: 'dair-ai/emotion'

resume_training: False

config_to_train: 'baseline'  # See all possible values in train.py
run_name: 'baseline'
epochs: 400
lambda_pag: 2.0
lambda_ce: 1.0
pag_samples_per_class: 24
